import os

UNITSYNCER_HOME = os.path.abspath(os.getenv("UNITSYNCER_HOME", os.curdir))
CORES = int(os.getenv("CORES", 1))

CAPABILITIES = {
    "textDocument": {
        "codeAction": {"dynamicRegistration": True},
        "codeLens": {"dynamicRegistration": True},
        "colorProvider": {"dynamicRegistration": True},
        "completion": {
            "completionItem": {
                "commitCharactersSupport": True,
                "documentationFormat": ["markdown", "plaintext"],
                "snippetSupport": True,
            },
            "completionItemKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                ]
            },
            "contextSupport": True,
            "dynamicRegistration": True,
        },
        "definition": {"dynamicRegistration": True},
        "documentHighlight": {"dynamicRegistration": True},
        "documentLink": {"dynamicRegistration": True},
        "documentSymbol": {
            "dynamicRegistration": True,
            "symbolKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                ]
            },
        },
        "formatting": {"dynamicRegistration": True},
        "hover": {
            "contentFormat": ["markdown", "plaintext"],
            "dynamicRegistration": True,
        },
        "implementation": {"dynamicRegistration": True},
        "onTypeFormatting": {"dynamicRegistration": True},
        "publishDiagnostics": {"relatedInformation": True},
        "rangeFormatting": {"dynamicRegistration": True},
        "references": {"dynamicRegistration": True},
        "rename": {"dynamicRegistration": True},
        "signatureHelp": {
            "dynamicRegistration": True,
            "signatureInformation": {"documentationFormat": ["markdown", "plaintext"]},
        },
        "synchronization": {
            "didSave": True,
            "dynamicRegistration": True,
            "willSave": True,
            "willSaveWaitUntil": True,
        },
        "typeDefinition": {"dynamicRegistration": True},
    },
    "workspace": {
        "applyEdit": True,
        "configuration": True,
        "didChangeConfiguration": {"dynamicRegistration": True},
        "didChangeWatchedFiles": {"dynamicRegistration": True},
        "executeCommand": {"dynamicRegistration": True},
        "symbol": {
            "dynamicRegistration": True,
            "symbolKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                ]
            },
        },
        "workspaceEdit": {"documentChanges": True},
        "workspaceFolders": True,
    },
}

RUST_CAPABILITIES = {
    "workspace": {
        "applyEdit": True,
        "workspaceEdit": {
            "documentChanges": True,
            "resourceOperations": ["create", "rename", "delete"],
            "failureHandling": "textOnlyTransactional",
            "normalizesLineEndings": True,
            "changeAnnotationSupport": {"groupsOnLabel": True},
        },
        "configuration": True,
        "didChangeWatchedFiles": {
            "dynamicRegistration": True,
            "relativePatternSupport": True,
        },
        "symbol": {
            "dynamicRegistration": True,
            "symbolKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                ]
            },
            "tagSupport": {"valueSet": [1]},
            "resolveSupport": {"properties": ["location.range"]},
        },
        "codeLens": {"refreshSupport": True},
        "executeCommand": {"dynamicRegistration": True},
        "didChangeConfiguration": {"dynamicRegistration": True},
        "workspaceFolders": True,
        "semanticTokens": {"refreshSupport": True},
        "fileOperations": {
            "dynamicRegistration": True,
            "didCreate": True,
            "didRename": True,
            "didDelete": True,
            "willCreate": True,
            "willRename": True,
            "willDelete": True,
        },
        "inlineValue": {"refreshSupport": True},
        "inlayHint": {"refreshSupport": True},
        "diagnostics": {"refreshSupport": True},
    },
    "textDocument": {
        "publishDiagnostics": {
            "relatedInformation": True,
            "versionSupport": False,
            "tagSupport": {"valueSet": [1, 2]},
            "codeDescriptionSupport": True,
            "dataSupport": True,
        },
        "synchronization": {
            "dynamicRegistration": True,
            "willSave": True,
            "willSaveWaitUntil": True,
            "didSave": True,
        },
        "completion": {
            "dynamicRegistration": True,
            "contextSupport": True,
            "completionItem": {
                "snippetSupport": True,
                "commitCharactersSupport": True,
                "documentationFormat": ["markdown", "plaintext"],
                "deprecatedSupport": True,
                "preselectSupport": True,
                "tagSupport": {"valueSet": [1]},
                "insertReplaceSupport": True,
                "resolveSupport": {
                    "properties": ["documentation", "detail", "additionalTextEdits"]
                },
                "insertTextModeSupport": {"valueSet": [1, 2]},
                "labelDetailsSupport": True,
            },
            "insertTextMode": 2,
            "completionItemKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                ]
            },
            "completionList": {
                "itemDefaults": [
                    "commitCharacters",
                    "editRange",
                    "insertTextFormat",
                    "insertTextMode",
                ]
            },
        },
        "hover": {
            "dynamicRegistration": True,
            "contentFormat": ["markdown", "plaintext"],
        },
        "signatureHelp": {
            "dynamicRegistration": True,
            "signatureInformation": {
                "documentationFormat": ["markdown", "plaintext"],
                "parameterInformation": {"labelOffsetSupport": True},
                "activeParameterSupport": True,
            },
            "contextSupport": True,
        },
        "definition": {"dynamicRegistration": True, "linkSupport": True},
        "references": {"dynamicRegistration": True},
        "documentHighlight": {"dynamicRegistration": True},
        "documentSymbol": {
            "dynamicRegistration": True,
            "symbolKind": {
                "valueSet": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                ]
            },
            "hierarchicalDocumentSymbolSupport": True,
            "tagSupport": {"valueSet": [1]},
            "labelSupport": True,
        },
        "codeAction": {
            "dynamicRegistration": True,
            "isPreferredSupport": True,
            "disabledSupport": True,
            "dataSupport": True,
            "resolveSupport": {"properties": ["edit"]},
            "codeActionLiteralSupport": {
                "codeActionKind": {
                    "valueSet": [
                        "",
                        "quickfix",
                        "refactor",
                        "refactor.extract",
                        "refactor.inline",
                        "refactor.rewrite",
                        "source",
                        "source.organizeImports",
                    ]
                }
            },
            "honorsChangeAnnotations": False,
        },
        "codeLens": {"dynamicRegistration": True},
        "formatting": {"dynamicRegistration": True},
        "rangeFormatting": {"dynamicRegistration": True},
        "onTypeFormatting": {"dynamicRegistration": True},
        "rename": {
            "dynamicRegistration": True,
            "prepareSupport": True,
            "prepareSupportDefaultBehavior": 1,
            "honorsChangeAnnotations": True,
        },
        "documentLink": {"dynamicRegistration": True, "tooltipSupport": True},
        "typeDefinition": {"dynamicRegistration": True, "linkSupport": True},
        "implementation": {"dynamicRegistration": True, "linkSupport": True},
        "colorProvider": {"dynamicRegistration": True},
        "foldingRange": {
            "dynamicRegistration": True,
            "rangeLimit": 5000,
            "lineFoldingOnly": True,
            "foldingRangeKind": {"valueSet": ["comment", "imports", "region"]},
            "foldingRange": {"collapsedText": False},
        },
        "declaration": {"dynamicRegistration": True, "linkSupport": True},
        "selectionRange": {"dynamicRegistration": True},
        "callHierarchy": {"dynamicRegistration": True},
        "semanticTokens": {
            "dynamicRegistration": True,
            "tokenTypes": [
                "namespace",
                "type",
                "class",
                "enum",
                "interface",
                "struct",
                "typeParameter",
                "parameter",
                "variable",
                "property",
                "enumMember",
                "event",
                "function",
                "method",
                "macro",
                "keyword",
                "modifier",
                "comment",
                "string",
                "number",
                "regexp",
                "operator",
                "decorator",
            ],
            "tokenModifiers": [
                "declaration",
                "definition",
                "readonly",
                "static",
                "deprecated",
                "abstract",
                "async",
                "modification",
                "documentation",
                "defaultLibrary",
            ],
            "formats": ["relative"],
            "requests": {"range": True, "full": {"delta": True}},
            "multilineTokenSupport": False,
            "overlappingTokenSupport": False,
            "serverCancelSupport": True,
            "augmentsSyntaxTokens": False,
        },
        "linkedEditingRange": {"dynamicRegistration": True},
        "typeHierarchy": {"dynamicRegistration": True},
        "inlineValue": {"dynamicRegistration": True},
        "inlayHint": {
            "dynamicRegistration": True,
            "resolveSupport": {
                "properties": [
                    "tooltip",
                    "textEdits",
                    "label.tooltip",
                    "label.location",
                    "label.command",
                ]
            },
        },
        "diagnostic": {
            "dynamicRegistration": True,
            "relatedDocumentSupport": False,
        },
    },
    "window": {
        "showMessage": {"messageActionItem": {"additionalPropertiesSupport": True}},
        "showDocument": {"support": True},
        "workDoneProgress": True,
    },
    "general": {
        "staleRequestSupport": {
            "cancel": True,
            "retryOnContentModified": [
                "textDocument/semanticTokens/full",
                "textDocument/semanticTokens/range",
                "textDocument/semanticTokens/full/delta",
            ],
        },
        "regularExpressions": {"engine": "ECMAScript", "version": "ES2020"},
        "markdown": {
            "parser": "marked",
            "version": "1.1.0",
            "allowedTags": [
                "ul",
                "li",
                "p",
                "code",
                "blockquote",
                "ol",
                "h1",
                "h2",
                "h3",
                "h4",
                "h5",
                "h6",
                "hr",
                "em",
                "pre",
                "table",
                "thead",
                "tbody",
                "tr",
                "th",
                "td",
                "div",
                "del",
                "a",
                "strong",
                "br",
                "img",
                "span",
            ],
        },
        "positionEncodings": ["utf-16"],
    },
    "notebookDocument": {
        "synchronization": {
            "dynamicRegistration": True,
            "executionSummarySupport": True,
        }
    },
    "experimental": {
        "snippetTextEdit": True,
        "codeActionGroup": True,
        "hoverActions": True,
        "serverStatusNotification": True,
        "colorDiagnosticOutput": True,
        "openServerLogs": True,
        "localDocs": True,
        "commands": {
            "commands": [
                "rust-analyzer.runSingle",
                "rust-analyzer.debugSingle",
                "rust-analyzer.showReferences",
                "rust-analyzer.gotoLocation",
                "editor.action.triggerParameterHints",
            ]
        },
    },
}

RUST_INIT_OPTIONS = {
    "cargoRunner": True,
    "runnables": {
        "extraEnv": None,
        "problemMatcher": ["$rustc"],
        "command": None,
        "extraArgs": [],
    },
    "statusBar": {"clickAction": "openLogs"},
    "server": {"path": None, "extraEnv": None},
    "trace": {"server": "verbose", "extension": False},
    "debug": {
        "engine": "auto",
        "sourceFileMap": {
            "/rustc/<id>": "${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust"
        },
        "openDebugPane": False,
        "engineSettings": {},
    },
    "restartServerOnConfigChange": False,
    "typing": {
        "continueCommentsOnNewline": True,
        "autoClosingAngleBrackets": {"enable": False},
    },
    "diagnostics": {
        "previewRustcOutput": False,
        "useRustcErrorCode": False,
        "disabled": [],
        "enable": True,
        "experimental": {"enable": False},
        "remapPrefix": {},
        "warningsAsHint": [],
        "warningsAsInfo": [],
    },
    "discoverProjectRunner": None,
    "showUnlinkedFileNotification": True,
    "showDependenciesExplorer": True,
    "assist": {"emitMustUse": False, "expressionFillDefault": "todo"},
    "cachePriming": {"enable": True, "numThreads": 0},
    "cargo": {
        "autoreload": True,
        "buildScripts": {
            "enable": True,
            "invocationLocation": "workspace",
            "invocationStrategy": "per_workspace",
            "overrideCommand": None,
            "useRustcWrapper": True,
        },
        "cfgs": {},
        "extraArgs": [],
        "extraEnv": {},
        "features": [],
        "noDefaultFeatures": False,
        "sysroot": "discover",
        "sysrootSrc": None,
        "target": None,
        "unsetTest": ["core"],
    },
    "checkOnSave": True,
    "check": {
        "allTargets": True,
        "command": "check",
        "extraArgs": [],
        "extraEnv": {},
        "features": None,
        "ignore": [],
        "invocationLocation": "workspace",
        "invocationStrategy": "per_workspace",
        "noDefaultFeatures": None,
        "overrideCommand": None,
        "targets": None,
    },
    "completion": {
        "autoimport": {"enable": True},
        "autoself": {"enable": True},
        "callable": {"snippets": "fill_arguments"},
        "fullFunctionSignatures": {"enable": False},
        "limit": None,
        "postfix": {"enable": True},
        "privateEditable": {"enable": False},
        "snippets": {
            "custom": {
                "Arc::new": {
                    "postfix": "arc",
                    "body": "Arc::new(${receiver})",
                    "requires": "std::sync::Arc",
                    "description": "Put the expression into an `Arc`",
                    "scope": "expr",
                },
                "Rc::new": {
                    "postfix": "rc",
                    "body": "Rc::new(${receiver})",
                    "requires": "std::rc::Rc",
                    "description": "Put the expression into an `Rc`",
                    "scope": "expr",
                },
                "Box::pin": {
                    "postfix": "pinbox",
                    "body": "Box::pin(${receiver})",
                    "requires": "std::boxed::Box",
                    "description": "Put the expression into a pinned `Box`",
                    "scope": "expr",
                },
                "Ok": {
                    "postfix": "ok",
                    "body": "Ok(${receiver})",
                    "description": "Wrap the expression in a `Result::Ok`",
                    "scope": "expr",
                },
                "Err": {
                    "postfix": "err",
                    "body": "Err(${receiver})",
                    "description": "Wrap the expression in a `Result::Err`",
                    "scope": "expr",
                },
                "Some": {
                    "postfix": "some",
                    "body": "Some(${receiver})",
                    "description": "Wrap the expression in an `Option::Some`",
                    "scope": "expr",
                },
            }
        },
    },
    "files": {"excludeDirs": [], "watcher": "client"},
    "highlightRelated": {
        "breakPoints": {"enable": True},
        "closureCaptures": {"enable": True},
        "exitPoints": {"enable": True},
        "references": {"enable": True},
        "yieldPoints": {"enable": True},
    },
    "hover": {
        "actions": {
            "debug": {"enable": True},
            "enable": True,
            "gotoTypeDef": {"enable": True},
            "implementations": {"enable": True},
            "references": {"enable": False},
            "run": {"enable": True},
        },
        "documentation": {"enable": True, "keywords": {"enable": True}},
        "links": {"enable": True},
        "memoryLayout": {
            "alignment": "hexadecimal",
            "enable": True,
            "niches": False,
            "offset": "hexadecimal",
            "size": "both",
        },
    },
    "imports": {
        "granularity": {"enforce": False, "group": "crate"},
        "group": {"enable": True},
        "merge": {"glob": True},
        "prefer": {"no": {"std": False}},
        "prefix": "plain",
    },
    "inlayHints": {
        "bindingModeHints": {"enable": False},
        "chainingHints": {"enable": True},
        "closingBraceHints": {"enable": True, "minLines": 25},
        "closureCaptureHints": {"enable": False},
        "closureReturnTypeHints": {"enable": "never"},
        "closureStyle": "impl_fn",
        "discriminantHints": {"enable": "never"},
        "expressionAdjustmentHints": {
            "enable": "never",
            "hideOutsideUnsafe": False,
            "mode": "prefix",
        },
        "lifetimeElisionHints": {"enable": "never", "useParameterNames": False},
        "maxLength": 25,
        "parameterHints": {"enable": True},
        "reborrowHints": {"enable": "never"},
        "renderColons": True,
        "typeHints": {
            "enable": True,
            "hideClosureInitialization": False,
            "hideNamedConstructor": False,
        },
    },
    "interpret": {"tests": False},
    "joinLines": {
        "joinAssignments": True,
        "joinElseIf": True,
        "removeTrailingComma": True,
        "unwrapTrivialBlock": True,
    },
    "lens": {
        "debug": {"enable": True},
        "enable": True,
        "forceCustomCommands": True,
        "implementations": {"enable": True},
        "location": "above_name",
        "references": {
            "adt": {"enable": False},
            "enumVariant": {"enable": False},
            "method": {"enable": False},
            "trait": {"enable": False},
        },
        "run": {"enable": True},
    },
    "linkedProjects": [],
    "lru": {"capacity": None, "query": {"capacities": {}}},
    "notifications": {"cargoTomlNotFound": True},
    "numThreads": None,
    "procMacro": {
        "attributes": {"enable": True},
        "enable": True,
        "ignored": {},
        "server": None,
    },
    "references": {"excludeImports": False},
    "rust": {"analyzerTargetDir": None},
    "rustc": {"source": None},
    "rustfmt": {
        "extraArgs": [],
        "overrideCommand": None,
        "rangeFormatting": {"enable": False},
    },
    "semanticHighlighting": {
        "doc": {"comment": {"inject": {"enable": True}}},
        "nonStandardTokens": True,
        "operator": {"enable": True, "specialization": {"enable": False}},
        "punctuation": {
            "enable": False,
            "separate": {"macro": {"bang": False}},
            "specialization": {"enable": False},
        },
        "strings": {"enable": True},
    },
    "signatureInfo": {"detail": "full", "documentation": {"enable": True}},
    "workspace": {
        "symbol": {"search": {"kind": "only_types", "limit": 128, "scope": "workspace"}}
    },
}
